base_info/urls.py
from django.urls import path

from base_info import views

urlpatterns = [
    path('person.html', views.PersonList.as_view(), name='person_list'),
    path('person-add-update.html', views.PersonAdd.as_view(), name='person_add'),
    path('person-del.html', views.PersonDel.as_view(), name='person_del'),
    path('person-add-update-<pk>.html', views.PersonUpdate.as_view(), name='person_update'),
    path('person-ztree.html', views.PersonZtree, name='person_ztree'),
    path('department.html', views.PartList.as_view(), name='part_list'),
    path('department-add-update.html', views.PartAdd.as_view(), name='part_add'),
    path('department-del.html', views.PartDel.as_view(), name='part_del'),
    path('department-add-update-<pk>.html', views.PartUpdate.as_view(), name='part_update'),

    path('shop.html', views.ShopList.as_view(), name='shop_list'),
    path('shop-add-update.html', views.ShopAdd.as_view(), name='shop_add'),
    path('shop-del.html', views.ShopDel.as_view(), name='shop_del'),
    path('shop-add-update-<pk>.html', views.ShopUpdate.as_view(), name='shop_update'),

    path('platform.html', views.PlatformList.as_view(), name='platform_list'),
    path('platform-add-update.html', views.PlatformAdd.as_view(), name='platform_add'),
    path('platformsize-add-update.html', views.Platform_sizeAdd.as_view(), name='platformsize_add'),
    # path('platformasstes-add-update.html', views.Platform_assetsAdd.as_view(), name='platformasstes_add'),
    # path('platform-del.html', views.PlatformDel.as_view(), name='platform_del'),
    # path('platform-add-update-<pk>.html', views.PlatformUpdate.as_view(), name='platform_update'),

]
app_name = 'base_info'

cmdb/urls.py
from django.urls import path

from cmdb import views

urlpatterns = [
    path('cmdb.html',views.CmdbListAll.as_view(),name='cmdb_list'),
    path('cmdb-del.html',views.CmdbDel.as_view(),name='cmdb_del'),
    path('cmdb-add-update.html',views.CmdbAdd.as_view(),name='cmdb_add'),
    path('cmdb-add-update-<int:pk>.html',views.CmdbUpdate.as_view(),name='cmdb_update'),
    path('cmdb-detail-<int:pk>.html',views.CmdbDetail.as_view(),name='cmdb_detail'),
    path('cmdb-export.html',views.CmdbExport.as_view(),name='cmdb_export'),
    path('cmdb-import.html',views.CmdbImport,name='cmdb_import'),
    path('cmdb-ztree.html', views.CmdbZtree, name='cmdb_ztree'),
    ]

app_name="cmdb"

xiaoi_ops/urls.py
from django.contrib import admin
from django.urls import path,include

from index.views import login_view, index, logout_view

urlpatterns = [
    path('admin/', admin.site.urls,name='admin'),
    path('',index),
    path('index.html',index,name='index'),
    path('login.html', login_view, name='login'),
    path('logout.html', logout_view, name='logout'),
    path('cmdb/', include('cmdb.urls', namespace="cmdb", ), ),
    path('pfdb/',include('pfdb.urls',namespace="pfdb")),
    path('gzdb/', include('gzdb.urls', namespace="gzdb")),
    path('base_info/', include('base_info.urls', namespace="base_info")),
    path('assets/', include('assets.urls', namespace="assets")),
    path('tb_log/',include('tb_log.urls',namespace="tb_log")),
    path('workorder/',include('work_order.urls',namespace="order")),
]

base_info/models.py
from django.db import models


# Create your models here.
class person(models.Model):
    uid = models.CharField(max_length=24, blank=False, verbose_name='工号',unique=True)
    name = models.CharField(max_length=24, blank=False, verbose_name='姓名')
    part = models.ForeignKey(to='department',to_field='id',on_delete=models.CASCADE,max_length=24, verbose_name='部门')
    mobile = models.CharField(max_length=11, verbose_name='手机号码')

    class Meta:
        db_table = "person_info"
        verbose_name = "员工信息"
        verbose_name_plural = '员工信息'


class department(models.Model):
    id = models.IntegerField(primary_key=True, blank=False, verbose_name='部门编号')
    name = models.CharField(max_length=16, blank=False, verbose_name='部门名称')

    class Meta:
        db_table = "department"
        verbose_name = "部门信息"
        verbose_name_plural = '部门信息'

    def __str__(self):
        return self.name


class shop(models.Model):
    name = models.CharField(max_length=24, blank=False, verbose_name='商家名称')
    user = models.CharField(max_length=24, blank=False, verbose_name='联系人')
    mobile = models.CharField(max_length=11, verbose_name='手机号码')
    addr = models.CharField(max_length=24, blank=True, verbose_name='商家地址')

    class Meta:
        db_table = "shop"
        verbose_name = "商家信息"
        verbose_name_plural = '商家信息'


class platform(models.Model):
    id =models.AutoField(primary_key=True, blank=False, verbose_name='id')
    name = models.CharField(max_length=24, verbose_name='设备类型')
    class Meta:
        db_table = "platform"
        verbose_name = "设备类型"
        verbose_name_plural = '设备类型'

    def __str__(self):
        return self.name


class platform_size(models.Model):

    name = models.CharField(max_length=24,verbose_name='设备型号')
    platform = models.ForeignKey(verbose_name="设备类型", to=platform, to_field='id', on_delete=models.CASCADE)
    class Meta:
        db_table = "platform_size"
        verbose_name = "设备型号"
        verbose_name_plural = '设备型号'
    def __str__(self):
        return self.name

# class platform_asstes(models.Model):
#
#     name = models.CharField(max_length=24,verbose_name='设备配置')
#     platform_size = models.ForeignKey(verbose_name="设备型号",to=platform_size,to_field='id',on_delete=models.CASCADE)
#     class Meta:
#         db_table = "platform_asstes"
#         verbose_name = "设备配置"
#         verbose_name_plural = '设备配置'

base_info/views.py
import json

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView, View

from xiaoi_ops import settings
from .form import *
from .models import *


# 人员管理视图
# Create your views here.
class PersonAdd(LoginRequiredMixin, CreateView):
    """增加"""
    model = person
    form_class = PersonForm
    template_name = 'base_info/person/person-add-update.html'
    success_url = reverse_lazy('base_info:person_list')


class PersonList(LoginRequiredMixin, ListView):
    model = person
    template_name = 'base_info/person/person.html'
    context_object_name = "person_list"
    paginate_by = settings.DISPLAY_PER_PAGE
    ordering = ("uid")

    def get_context_data(self, *, object_list=None, **kwargs):

        search_data = self.request.GET.copy()
        print(search_data)
        try:
            search_data.pop("page")

        except BaseException as e:
            pass
        print(search_data.dict())
        print(search_data.urlencode())
        # context.update(search_data.dict())
        # 左侧导航站展开  "asset_active": "active",
        context = {
            "search_data": search_data.urlencode(),
            "base_info_class": 'active',
        }
        kwargs.update(context)
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        if self.request.GET.get('name'):
            query = self.request.GET.get('name', None)

            try:
                queryset =super().get_queryset().filter(Q(name=query) | Q(uid=query) |Q(part_id=query)).order_by('-uid')
            except BaseException:
                queryset =super().get_queryset().filter(Q(name=query) | Q(uid=query)).order_by('-uid')
        else:
            queryset = super().get_queryset()
        return queryset



class PersonUpdate(LoginRequiredMixin, UpdateView):
    model = person
    success_url = reverse_lazy('base_info:person_list')
    form_class = PersonForm
    template_name = 'base_info/person/person-add-update.html'


class PersonDel(LoginRequiredMixin, View):
    model = person

    def post(self, request):
        ret = {'status': True, 'error': None}
        try:
            if request.POST.get('nid'):
                id = request.POST.get('nid', None)
                person.objects.get(id=id).delete()
            else:
                ids = request.POST.getlist('id', None)
                if len(ids) == 0:
                    ret['status'] = False
                    ret['error'] = '请选者删除的条目'
                else:
                    idstring = ','.join(ids)
                    person.objects.extra(where=['id IN (' + idstring + ')']).delete()
        except Exception as e:
            ret['status'] = False
            ret['error'] = '删除错误'.format(e)
        finally:
            return HttpResponse(json.dumps(ret))


def PersonZtree(request):
    """
    获取 区域 资产树 的相关数据
    :param request:
    :return:
    """

    manager = department.objects.values().distinct()
    data = [{"id": "1111", "pId": "0", "name": "部门"}, ]
    for i in manager:
        data.append({"id": i['id'], "pId": "1111", "name": i['name']}, )
    return HttpResponse(json.dumps(data), content_type='application/json')
# 部门管理视图
class PartAdd(LoginRequiredMixin, CreateView):
    """增加"""
    model = department
    form_class = DepartmentForm
    template_name = 'base_info/department/department-add-update.html'
    success_url = reverse_lazy('base_info:part_list')


class PartList(LoginRequiredMixin, ListView):
    model = department
    template_name = 'base_info/department/department.html'
    context_object_name = "part_list"
    paginate_by = settings.DISPLAY_PER_PAGE
    ordering = ("id")


    def get_context_data(self, *, object_list=None, **kwargs):

        search_data = self.request.GET.copy()
        print(search_data)
        try:
            search_data.pop("page")

        except BaseException as e:
            pass
        print(search_data.dict())
        print(search_data.urlencode())
        # context.update(search_data.dict())
        # 左侧导航站展开  "asset_active": "active",
        context = {
            "search_data": search_data.urlencode(),
            "base_info_class": 'active',
        }
        kwargs.update(context)
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        if self.request.GET.get('name'):
            query = self.request.GET.get('name', None)
            queryset =super().get_queryset().filter(Q(name=query) | Q(id=query) |Q(part=query)).order_by('-id')
        else:
            queryset = super().get_queryset()
        return queryset



class PartUpdate(LoginRequiredMixin, UpdateView):
    model = department
    success_url = reverse_lazy('base_info:department_list')
    form_class = DepartmentForm
    template_name = 'base_info/department/department-add-update.html'


class PartDel(LoginRequiredMixin, View):
    model = department

    def post(self, request):
        ret = {'status': True, 'error': None}
        try:
            if request.POST.get('nid'):
                id = request.POST.get('nid', None)
                department.objects.get(id=id).delete()
            else:
                ids = request.POST.getlist('id', None)
                if len(ids) == 0:
                    ret['status'] = False
                    ret['error'] = '请选者删除的条目'
                else:
                    idstring = ','.join(ids)
                    department.objects.extra(where=['id IN (' + idstring + ')']).delete()
        except Exception as e:
            ret['status'] = False
            ret['error'] = '删除错误'.format(e)
        finally:
            return HttpResponse(json.dumps(ret))

#商家管理视图
class ShopAdd(LoginRequiredMixin, CreateView):
    """增加"""
    model = shop
    form_class = ShopForm
    template_name = 'base_info/shop/shop-add-update.html'
    success_url = reverse_lazy('base_info:shop_list')


class ShopList(LoginRequiredMixin, ListView):
    model = shop
    template_name = 'base_info/shop/shop.html'
    context_object_name = "shop_list"
    paginate_by = settings.DISPLAY_PER_PAGE
    ordering = ("id")

    def get_context_data(self, *, object_list=None, **kwargs):

        search_data = self.request.GET.copy()
        print(search_data)
        try:
            search_data.pop("page")

        except BaseException as e:
            pass
        print(search_data.dict())
        print(search_data.urlencode())
        # context.update(search_data.dict())
        # 左侧导航站展开  "asset_active": "active",
        context = {
            "search_data": search_data.urlencode(),
            "base_info_class": 'active',
        }
        kwargs.update(context)
        return super().get_context_data(**kwargs)




class ShopUpdate(LoginRequiredMixin, UpdateView):
    model = shop
    success_url = reverse_lazy('base_info:shop_list')
    form_class = ShopForm
    template_name = 'base_info/shop/shop-add-update.html'


class ShopDel(LoginRequiredMixin, View):
    model = shop

    def post(self, request):
        ret = {'status': True, 'error': None}
        try:
            if request.POST.get('nid'):
                id = request.POST.get('nid', None)
                shop.objects.get(id=id).delete()
            else:
                ids = request.POST.getlist('id', None)
                if len(ids) == 0:
                    ret['status'] = False
                    ret['error'] = '请选者删除的条目'
                else:
                    idstring = ','.join(ids)
                    shop.objects.extra(where=['id IN (' + idstring + ')']).delete()
        except Exception as e:
            ret['status'] = False
            ret['error'] = '删除错误'.format(e)
        finally:
            return HttpResponse(json.dumps(ret))


#设备类型视图
#
class PlatformList(LoginRequiredMixin, ListView):
    template_name = 'base_info/platform/platform.html'
    context_object_name = "dic_list"
    paginate_by = settings.DISPLAY_PER_PAGE

    def get_context_data(self, *, object_list=None, **kwargs):

        search_data = self.request.GET.copy()
        print(search_data)
        try:
            search_data.pop("page")

        except BaseException as e:
            pass
        print(search_data.dict())
        print(search_data.urlencode())
        # context.update(search_data.dict())
        # 左侧导航站展开  "asset_active": "active",
        context = {
            "search_data": search_data.urlencode(),
            "base_info_class": 'active',
        }
        kwargs.update(context)
        return super().get_context_data(**kwargs)

    def get_queryset(self):

        dic_list=[]
        P = platform.objects.all()
        # S = platform_size.objects.all()
        for i in P:
            L = []
            dic = {}
            S = platform_size.objects.filter(platform__name=i.name)
            for x in S:
                L.append(x.name)
            dic[i.name] = L
            dic_list.append(dic)
        print(dic_list)
        # return render(request, 'base_info/platform/platform.html', {'dic': dic})
        return dic_list

class PlatformAdd(LoginRequiredMixin, CreateView):
    """增加"""
    model = platform
    form_class = PlatformForm
    template_name = 'base_info/platform/platform-add-update.html'
    success_url = reverse_lazy('base_info:platform_list')

class Platform_sizeAdd(LoginRequiredMixin, CreateView):
    """增加"""
    model = platform_size
    form_class = Platform_sizeForm
    template_name = 'base_info/platform/platformsize-add-update.html'
    success_url = reverse_lazy('base_info:platform_list')

# class Platform_assetsAdd(LoginRequiredMixin, CreateView):
#     """增加"""
#     model = platform_asstes
#     form_class = Platform_asstesForm
#     template_name = 'base_info/platform/platform_asstes-add-update.html'
#     success_url = reverse_lazy('base_info:platformasstes_list')
#     context_object_name = 'name'
#

templates/base_info/platform/platform-add-update.html
{% extends "base.html" %}
{% block  title %}设备{% endblock %}
{% block header-css %}
    {% load bootstrap3 %}
{% endblock %}


{% block page-content %}

    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>设备</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="/index.html">主页</a>
                </li>
                <li>
                    <a href="cmdb.html">设备管理</a>
                </li>
                <li class="active">
                    <strong>设备</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>


    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>设备</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li><a href="#">选项 1</a>
                            </li>
                            <li><a href="#">选项 2</a>
                            </li>
                        </ul>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <form method="post" class="form-horizontal">
                        {% csrf_token %}
                        {% if form.no_field_errors %}
                            <div class="alert alert-danger" style="margin: 20px auto 0px">
                                {{ form.non_field_errors }}
                            </div>
                        {% endif %}


                        <div class="form-group">
                            <div class="col-sm-10 col-sm-offset-0">
                                <h3>基本信息</h3>
                                {% bootstrap_field form.name layout="horizontal" %}
                            </div>
                        </div>
                        <div class="hr-line-dashed"></div>
                        <div class="hr-line-dashed"></div>

                        <div class="form-group">
                            <div class="col-sm-4 col-sm-offset-3">

                                {% bootstrap_button "保存" button_type="submit" button_class="btn-primary" %}

                                <a class="btn btn-default" href="{% url 'base_info:platform_list' %}">取消</a>
                            </div>
                        </div>
                    </form>


                </div>
            </div>
        </div>

    </div>


    {% block footer-js %}
        <script>
            $(document).ready(function () {
                $('.select2').select2();
                $("#id_tags").select2({
                    tags: true,
                    closeOnSelect: false
                });
            });


        </script>
    {% endblock %}

{% endblock %}

templates/base_info/platform/platform.html
{% extends "base.html" %}
{% load  static %}
{% load  bootstrap3 %}
{% block header-css %}
    <style type="text/css">


        div#rMenu {
            position: absolute;
            visibility: hidden;
            text-align: left;
            top: 100%;
            left: 0;
            z-index: 1000;
            float: left;
            padding: 5px 0;
            margin: 2px 0 0;
            list-style: none;
            background-clip: padding-box;
        }

        div#rMenu li {
            margin: 1px 0;
            cursor: pointer;
        {#list-style: none outside none;#}
        }

        .dropdown a:hover {
            background-color: #f1f1f1
        }
    </style>

{% endblock %}

{% block  title %}设备信息{% endblock %}



{% block page-content %}
    <div class="row wrapper border-bottom white-bg page-heading ">
        <div class="col-lg-10">
            <h2>基础信息管理</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{% url "index" %}">主页</a>
                </li>
                <li>
                    <a>基础资料</a>
                </li>
                <li class="active">
                    <strong>设备信息</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2" id="split-left">
        </div>
    </div>

    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-11" id="split-right"     style="width: 100%" >

                <div class="ibox float-e-margins">

                    <div class="ibox-title">
                        <h5>设备信息</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-wrench"></i>
                            </a>
                            <ul class="dropdown-menu dropdown-user">
                                <li><a href="#">选项 1</a>
                                </li>
                                <li><a href="#">选项 2</a>
                                </li>
                            </ul>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">

                        <div class="table-responsive">
                                <a href="{% url  'base_info:platform_add' %}" class=" btn btn-sm btn-primary ">
                                    添加设备类型</a>
                                  <a href="{% url  'base_info:platformsize_add' %}" class=" btn btn-sm btn-primary ">
                                    添加设备型号</a>
{#                                <a class="btn btn-sm btn-danger  cmdb_all_del"#}
{#                                >批量删除#}
{#                                </a>#}
{#                            <form id="del_form_cmdb_all" class="form-horizontal  "#}
{#                                  action="{% url "cmdb:cmdb_export" %}" method="post">#}
{#                                {% csrf_token %}#}


                                <table class="table table-striped table-bordered table-hover dataTables-cmdb">
                                    <thead>
                                    <tr>

                                        <th>设备类型</th>
                                        <th>设备型号</th>
                                    </tr>
                                    </thead>
                                    <tbody>



                                    {% for i in dic_list %}
                                        {% for key,value in i.items %}

                                        <tr class="gradeA" id="{{ key }}">
                                            <td class="center">{{ key }}</td>
                                            <td class="center">{% for y in value %}
                                                {{ y }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

                                            {% endfor %}
                                             </td>
{#                                            <td><a class="btn btn-primary  btn-xs "#}
{#                                                   href="{% url 'base_info:platformsize_add' %}">添加设备型号</a>#}
{#                                                <a class="btn btn-danger  btn-xs  person_del">删除</a>#}
                                            </td>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                    {% endfor %}
                                    </tbody>

                                </table>

                                <div>


                                    <ul class="pagination">
                                        <li><a href="{% url "base_info:platform_list" %}?page=1">首页 </a></li>
                                        {% if  page_obj.has_previous %}
                                            <li>
                                                <a href="{% url "base_info:platform_list" %}?page={{ page_obj.previous_page_number }}">
                                                    上一页 </a></li>
                                        {% else %}
                                            <li class="disabled"><a> 上一页 </a></li>
                                        {% endif %}

                                        {% for p in paginator.page_range %}
                                                {% if p == page_obj.number %}
                                                    <li class="active"><a
                                                            href="{% url "base_info:platform_list" %}?page={{ p }}"> {{ p }} </a>
                                                    </li>
                                                {% else %}
                                                    <li>
                                                        <a href="{% url "base_info:platform_list" %}?page={{ p }}"> {{ p }} </a>
                                                    </li>
                                                {% endif %}

                                        {% endfor %}


                                        {% if  page_obj.has_next %}
                                            <li>
                                                <a href="{% url "base_info:platform_list" %}?page={{ page_obj.next_page_number }}">
                                                    下一页 </a></li>
                                        {% endif %}
                                        <li>
                                            <a href="{% url "base_info:platform_list" %}?page={{ page_obj.paginator.num_pages }}">尾页 </a>
                                        </li>
                                        <li><span
                                                style="color: #0a0a0a">总: &nbsp;{{ page_obj.paginator.num_pages }} 页 </span>
                                        </li>

                                    </ul>
                                    </center>
                                </div> <!--页码 -->


                            </form>


                        </div>

                    </div>


                </div>
            </div>
        </div>
    </div>



    {% block footer-js %}
        <script type="text/javascript" src="{% static 'js/plugins/ztree/jquery.ztree.all.min.js' %}"></script>
        <script src="{% static 'js/jquery.form.min.js' %}"></script>


        <script type="text/javascript">
            $(function () {

                $(document).on('click', '.person_del', function () {
                    var id = $(this).parent().parent().attr('id');
                    swal({
                        title: "你确定删除",
                        text: "你将无法恢复",
                        type: "warning",
                        showCancelButton: true,
                        confirmButtonColor: "#DD6B55",
                        confirmButtonText: "确定",
                        closeOnConfirm: false
                    }, function () {
                        $.ajax({
                            headers: {"X-CSRFToken": '{{ csrf_token }}'},
                            url: "department-del.html",
                            type: 'POST',
                            data: {'nid': id},
                            success: function (data) {
                                var obj = JSON.parse(data);
                                if (obj.status) {
                                    swal({title: "删除", text: "已成功删除", type: "success"}, function () {
                                        window.location.reload();
                                    })
                                } else {
                                    swal("错误", "删除" + "[ " + obj.error + " ]" + "遇到错误", "error");
                                }
                            }
                        });


                    });

                });

                $(document).on('click', '.cmdb_all_del', function () {

                    swal({

                        title: "你确定删除",
                        text: "你将无法恢复",
                        type: "warning",
                        showCancelButton: true,
                        confirmButtonColor: "#DD6B55",
                        confirmButtonText: "确定",

                        closeOnConfirm: false
                    }, function () {
                        $.ajax({
                            headers: {"X-CSRFToken": '{{ csrf_token }}'},
                            url: "department-del.html",
                            type: 'POST',
                            data: $('#del_form_cmdb_all').serialize(),
                            success: function (data) {
                                var obj = JSON.parse(data);
                                if (obj.status) {
                                    swal({title: "删除", text: "已成功删除", type: "success"}, function () {
                                        window.location.reload();
                                    })
                                } else {
                                    swal("错误", "删除" + "[ " + obj.error + " ]" + "遇到错误", "error");
                                }
                            }
                        });


                    });
                });


            });
        </script>

    {% endblock %}

    {% block footer-js-ajax %}
    {% endblock %}

{% endblock %}