assets/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django.urls import path

from assets import views

app_name = 'assets'

urlpatterns = [
    path('assets.html', views.AssetsList.as_view(), name='assets_list'),
    path('assets-add-update.html', views.AssetsAdd.as_view(), name='assets_add'),
    path('assets-update-<pk>.html', views.AssetsUpdateDtail.as_view(), name='assets_update'),
    path('assets-detail-<pk>.html', views.AssetsDetail.as_view(), name='assets_detail'),
    path('assets-wx-<pk>.html', views.repair, name='assets_log'),
    path('assets-add-update-g-<pk>.html', views.AssetsUpdate.as_view(), name='assets_update_g'),
    path('assets-add-update-o-<pk>.html', views.AssetsUpdate.as_view(), name='assets_update_o'),
    path('assets-add-update-i-<pk>.html', views.AssetsUpdatein.as_view(), name='assets_update_i'),
    path('assets-add-update-p-<pk>.html', views.AssetsUpdatein.as_view(), name='assets_update_p'),
    path('getdata.html', views.getdata, name='getdate'),
    path('assets-ztree.html', views.AssetsZtree, name='assets_ztree'),
    path('assets-export.html', views.excel_export, name='assets_export'),
    path('assets-import.html',views.AssetsImport,name='assets_import'),
    path('assets-count.html', views.assets_count, name='assets_count'),
]

cmdb/urls.py
from django.urls import path

from cmdb import views

urlpatterns = [
    path('cmdb.html',views.CmdbListAll.as_view(),name='cmdb_list'),
    path('cmdb-del.html',views.CmdbDel.as_view(),name='cmdb_del'),
    path('cmdb-add-update.html',views.CmdbAdd.as_view(),name='cmdb_add'),
    path('cmdb-add-update-<int:pk>.html',views.CmdbUpdate.as_view(),name='cmdb_update'),
    path('cmdb-detail-<int:pk>.html',views.CmdbDetail.as_view(),name='cmdb_detail'),
    path('cmdb-export.html',views.CmdbExport.as_view(),name='cmdb_export'),
    path('cmdb-import.html',views.CmdbImport,name='cmdb_import'),
    path('cmdb-ztree.html', views.CmdbZtree, name='cmdb_ztree'),
    ]

app_name="cmdb"

tb_log/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.urls import path
from tb_log import views

app_name = 'tb_log'

urlpatterns = [
    path('tb_log-<kw>-<pk>-<user>.html', views.logcreate, name='tb_log_create'),
    path('tb_log.html', views.LogView.as_view(), name='tb_log_list'),
    # path('assets-add-update.html', views.AssetsAdd.as_view(), name='assets_add'),
    # path('assets-detail-<pk>.html', views.AssetsDetail.as_view(), name='assets_detail'),
    # path('assets-add-update-g-<pk>.html', views.AssetsUpdate.as_view(), name='assets_update_g'),
    # path('assets-add-update-o-<pk>.html', views.AssetsUpdate.as_view(), name='assets_update_o'),
    # path('assets-add-update-i-<pk>.html', views.AssetsUpdatein.as_view(), name='assets_update_i'),
    # path('getdata.html', views.getdata, name='getdate'),
]

xiaoi_ops/urls.py
from django.contrib import admin
from django.urls import path,include

from index.views import login_view, index, logout_view

urlpatterns = [
    path('admin/', admin.site.urls,name='admin'),
    path('',index),
    path('index.html',index,name='index'),
    path('login.html', login_view, name='login'),
    path('logout.html', logout_view, name='logout'),
    path('cmdb/', include('cmdb.urls', namespace="cmdb", ), ),
    path('pfdb/',include('pfdb.urls',namespace="pfdb")),
    path('gzdb/', include('gzdb.urls', namespace="gzdb")),
    path('base_info/', include('base_info.urls', namespace="base_info")),
    path('assets/', include('assets.urls', namespace="assets")),
    path('tb_log/',include('tb_log.urls',namespace="tb_log")),
    path('workorder/',include('work_order.urls',namespace="order")),
]

assets/models.py
from django.db import models

from base_info.models import platform,platform_size


# Create your models here.
class active(models.Model):
    name = models.CharField(max_length=24,verbose_name='状态',unique=True)

    class Meta:
        db_table = 'active'
        verbose_name = '资产状态'
        verbose_name_plural = verbose_name
    def __str__(self):
        return self.name


class assets(models.Model):
    active = models.ForeignKey(to=active, to_field='id', on_delete=models.CASCADE, verbose_name='状态', default=1)
    uid = models.CharField(max_length=24,primary_key=True,verbose_name='资产编号',db_index=True)
    pid = models.CharField(verbose_name='设备号', max_length=24, null=True, blank=True)
    utype = models.ForeignKey(to=platform,on_delete=models.CASCADE,to_field='id',verbose_name='设备类型')
    usize = models.ForeignKey(to=platform_size,on_delete=models.CASCADE,to_field='id',verbose_name='设备型号')
    user = models.CharField(verbose_name='使用人',max_length=24,db_index=True,null=True,blank=True)
    upart = models.CharField(verbose_name='部门', max_length=24, db_index=True, null=True, blank=True)
    addr = models.CharField(verbose_name='存放地点', max_length=24, null=True, blank=True, default='库房')
    cpu = models.CharField(max_length=64, verbose_name='CPU', null=True, blank=True)
    mem = models.CharField(max_length=64, verbose_name='内存', null=True, blank=True)
    disk = models.CharField(max_length=256, verbose_name="硬盘", null=True, blank=True)
    sn = models.CharField(verbose_name='SN号', max_length=24, null=True, blank=True)
    nmac = models.CharField(verbose_name='有线mac', max_length=24, null=True, blank=True)
    wmac = models.CharField(verbose_name='无线mac', max_length=24, null=True, blank=True)
    ctime = models.DateField(verbose_name='入库时间')
    otime = models.DateField(verbose_name='领（借）用时间', null=True, blank=True)
    gtime = models.DateField(verbose_name='归还(报废)时间', null=True, blank=True)
    ps = models.CharField(verbose_name='备注', max_length=24, null=True, blank=True)





    class Meta:
        db_table = "assets"
        verbose_name = "固定资产"
        verbose_name_plural = '固定资产'
        permissions = {
            ('read_assets', u"quit"
                            u"只读资产库"),
        }

    def __str__(self):
        return str(self.uid)

# active.objects.create(name='在库')
# active.objects.create(name='领用')
# active.objects.create(name='借用')
# active.objects.create(name='维修')
# active.objects.create(name='报废')
#     # def __str__(self):
    #     return self.name

pfdb/models.py
# Create your models here.
from django.db import models

class pfdb(models.Model):

    id = models.AutoField(primary_key=True,verbose_name="id")
    platfrom_name = models.CharField(max_length=64,verbose_name="平台名称")
    platfrom_url = models.URLField(max_length=128,verbose_name="平台地址")
    platfrom_ps = models.CharField(max_length=128, verbose_name="备注")

    class Meta:
        db_table ="pfdb"
        verbose_name="平台管理"
        verbose_name_plural = '平台管理'

    def __str__(self):
        return self.platfrom_name

tb_log/models.py
from django.db import models

# Create your models here.
from assets.models import assets

class tb_log(models.Model):

    uid = models.ForeignKey(to=assets,to_field='uid',on_delete=models.CASCADE,verbose_name='资产编号')
    log_info = models.TextField(verbose_name='操作记录')
    user = models.CharField(verbose_name='操作人', max_length=24)

work_order/models.py
# Create your models here.
from django.db import models

class order(models.Model):

    STAUTS_CHOICES=(
        ("待处理",'待处理'),
        ('已完成','已完成'),
    )

    event_name = models.CharField(max_length=64,verbose_name='事件名称')
    event_ps = models.CharField(max_length=4000,verbose_name='事件描述')
    person = models.CharField(max_length=14,verbose_name='处理人')
    event_starttime = models.DateField(verbose_name='事件创建时间',auto_now_add=True)
    event_updatetime = models.DateField(verbose_name='事件创建时间',auto_now=True)
    event_endtime = models.DateField(verbose_name='计划完成时间')
    event_progress = models.CharField(verbose_name='进度',max_length=24)
    event_status = models.CharField(verbose_name='时间状态',choices=STAUTS_CHOICES,max_length=24)


    class  Meta:
        db_table ="order"
        verbose_name="工作日志"
        verbose_name_plural = verbose_name


    def __str__(self):
        return self.id

assets/views.py
import json
import re
import time

from django.shortcuts import render,get_object_or_404,HttpResponseRedirect
# Create your views here.
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView, DetailView
from xiaoi_ops import settings
from  .models import *
from .form import AssetsForm,AssetsForm_give,AssetsForm_in
from django.core import serializers
from django.db.models import Q
from tb_log.models import tb_log
from cmdb.form import FileForm
from django.contrib.auth.decorators import login_required


class AssetsList(LoginRequiredMixin,ListView):
    template_name = 'assets/assets.html'
    model = assets
    context_object_name = 'assets_list'
    paginate_by = settings.DISPLAY_PER_PAGE
    ordering = ("active_id")


    def get_context_data(self, *, object_list=None, **kwargs):

        search_data = self.request.GET.copy()
        # print(search_data)
        # 高级分页
        context = super().get_context_data(**kwargs)
        paginator = context.get('paginator')

        page = context.get('page_obj')
        is_paginated = context.get('is_paginated')
        pagination_data = self.pagination_data(paginator, page, is_paginated)
        try:
            search_data.pop("page")

        except BaseException as e:
            pass
        # print(search_data.dict())
        # print(search_data.urlencode())
        # context.update(search_data.dict())
        # 左侧导航站展开  "asset_active": "active",
        context = {
            "search_data": search_data.urlencode(),
            "assets_class": 'active',
        }
        kwargs.update(context)
        kwargs.update(pagination_data)
        return super().get_context_data(**kwargs)



    def get_queryset(self):
        if self.request.GET.get('name'):
            query = self.request.GET.get('name', None)
            # print(query)
            try:
                queryset = super().get_queryset().filter(
                        Q(user__icontains=query) | Q(uid__icontains=query) | Q(active_id__icontains=query) | Q(
                            pid__icontains=query)).order_by('pid')
                # print('......')
            except BaseException as e:
                # print(e)
                queryset = super().get_queryset().filter(
                    Q(user__icontains=query) | Q(uid__icontains=query) | Q(pid__icontains=query)).order_by('pid')
        else:
            queryset = super().get_queryset()
        return queryset


    def pagination_data(self, paginator, page, is_paginated):

        if not is_paginated:
            return {}

        left = []
        right = []

        left_has_more = False
        right_has_more = False

        first = False
        last = False
        # 当前页码
        page_number = page.number
        # 总页数
        total_pages = paginator.num_pages
        # 页码列表
        page_range = paginator.page_range

        if page_number == 1:
            right = page_range[page_number:page_number + 3]

            if right[-1] < total_pages - 1:
                right_has_more = True

            if right[-1] < total_pages:
                last = True

        elif page_number == total_pages:
            left = page_range[(page_number - 4) if (page_number - 4) > 0 else 0:page_number - 1]

            if left[0] > 2:
                left_has_more = True

            if left[0] > 1:
                first = True

        else:

            left = page_range[(page_number - 4) if (page_number - 4) > 0 else 0:page_number - 1]
            right = page_range[page_number:page_number + 3]

            if right[-1] < total_pages - 1:
                right_has_more = True

            if right[-1] < total_pages:
                last = True

            if left[0] > 2:
                left_has_more = True

            if left[0] > 1:
                first = True

        data = {
            'left': left,
            'right': right,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'first': first,
            'last': last,
        }

        return data


class AssetsAdd(LoginRequiredMixin, CreateView):
    """增加"""
    model = assets
    form_class = AssetsForm
    template_name = 'assets/assets-add-update.html'
    # success_url = reverse_lazy('assets:assets_list')

    def post(self, request, *args, **kwargs):
        # print(self.request.POST)
        pk=request.POST['uid']
        # print(pk)
        self.success_url=reverse_lazy('tb_log:tb_log_create',kwargs={'pk':pk,'kw':'c','user':'c'})
        return super().post(request, *args, **kwargs)


class AssetsUpdateDtail(LoginRequiredMixin, UpdateView):
    model = assets
    form_class = AssetsForm
    template_name = 'assets/assets-update.html'
    context_object_name = 'obj'
    # success_url = reverse_lazy('assets:assets_list')
    def post(self, request, *args, **kwargs):
        # print(self.request.POST)
        pk=request.POST['uid']
        # print(pk)
        self.success_url=reverse_lazy('tb_log:tb_log_create',kwargs={'pk':pk,'kw':'u','user':'c'})
        return super().post(request, *args, **kwargs)


@login_required(login_url="login.html")
def getdata(request):
    pk = request.GET['pk']
    plat = get_object_or_404(platform, pk=pk)
    size = plat.platform_size_set.all()
    data = serializers.serialize('json', size)
    # print(data)
    return HttpResponse(data, content_type='application/json')


class AssetsDetail(LoginRequiredMixin,DetailView):
    model = assets
    template_name = 'assets/assets-detail.html'

    def get_context_data(self, **kwargs):
        pk = self.kwargs.get(self.pk_url_kwarg,None)
        detail = assets.objects.get(uid=pk)
        text = {
            "detail":detail,
            "nid":pk,
        }
        kwargs.update(text)
        return super().get_context_data(**kwargs)



class AssetsUpdate(LoginRequiredMixin,UpdateView):
    '''借用和领用资产'''
    model = assets
    form_class = AssetsForm_give
    template_name = 'assets/assets-add-update-give.html'
    # success_url = reverse_lazy('assets:assets_list')

    def post(self, request, *args, **kwargs):


        # print(pk)

        # print(reverse_lazy('tb_log:tb_log_create',kwargs={'pk':pk,}))

        # print(self.request.path)
        b=self.request.path
        a=self.request.POST.copy()
        ret=re.search('-g-',b)
        pk = self.request.path.split('.html')[0].split('-')[-1]

        user = self.request.POST['user']
        if assets.objects.get(uid=pk).active_id==1:
            if ret is None:
                a['active'] = 3
                self.success_url=reverse_lazy('tb_log:tb_log_create',kwargs={'pk':pk,'kw':'o','user':user})
            else:
                a['active'] = 2
                self.success_url=reverse_lazy('tb_log:tb_log_create',kwargs={'pk':pk,'kw':'l','user':user})
            # print(a)
            self.request.POST = a
        else :
            return HttpResponse('请先归还资产')

        return super().post(request, *args, **kwargs)


class AssetsUpdatein(LoginRequiredMixin,UpdateView):
    '''归还资产和资产报废'''
    model = assets
    form_class = AssetsForm_in
    template_name = 'assets/assets-add-update-in.html'
    # success_url = reverse_lazy('assets:assets_list')

    def post(self, request, *args, **kwargs):
        b=self.request.path
        ret = re.search('-i-', b)
        pk = self.request.path.split('.html')[0].split('-')[-1]
        a=self.request.POST.copy()

        if ret :
            a['active']=1
            a['user']=''
            a['otime']=''
            self.success_url=reverse_lazy('tb_log:tb_log_create',kwargs={'pk':pk,'kw':'i','user':'c'})

        else:
            if assets.objects.get(uid=pk).active_id == 1 or assets.objects.get(uid=pk).active_id == 5:
                a['active'] = 5
                a['user'] = ''
                a['otime'] = ''
                self.success_url = reverse_lazy('tb_log:tb_log_create', kwargs={'pk': pk, 'kw': 'p', 'user': 'c'})

            else:
                return HttpResponse('请先归还资产')
        self.request.POST=a
        return super().post(request, *args, **kwargs)


@login_required
def repair(request,**kwargs):
    '''维修资产'''
    if request.method == 'GET':
        return render(request,'assets/wx_log.html')

    if request.method == 'POST':

        pk = request.path.split('.html')[0].split('-')[-1]
        str_id = request.POST['wx']

        if assets.objects.get(uid=pk).active_id==1:

            assets.objects.filter(uid=pk).update(active_id=4)

        else :
            return HttpResponse('请先归还资产')
        str1=str(pk)+'在'+time.strftime("%Y-%m-%d",time.localtime(time.time()))+'报修'+'  报修原因：'+str_id
        try:

            user = request.user.username
            tb_log.objects.create(uid_id=pk, log_info=str1, user=user)
        except BaseException :
                return HttpResponse('数据录入成功，操作日志录入失败，请联系开发人员')
        else:
            return HttpResponseRedirect(reverse_lazy('assets:assets_list'))


@login_required
def AssetsZtree(request):
    """
    获取 区域 资产树 的相关数据
    :param request:
    :return:
    """

    manager = active.objects.values()
    data = [{"id": "1111", "pId": "0", "name": "状态"}, ]
    for i in manager:
        # print(i['id'])
        data.append({"id": i['id'], "pId": "1111", "name": i['name'], "page": "xx.action"}, )
    return HttpResponse(json.dumps(data), content_type='application/json')


@login_required
def excel_export(request):
    '''文件导出'''
    import xlwt
    from io import BytesIO

    if request.method == 'GET':
        list_obj = assets.objects.all().order_by('utype_id','active_id')
        style = xlwt.XFStyle()
        style.num_format_str='M/D/YY'
        if list_obj:
            fields = [field for field in assets._meta.fields]
            print(fields)

            header = [field.verbose_name for field in fields]

templates/assets/assets-add-update-give.html
{% extends "base.html" %}
{% block  title %}资产{% endblock %}
{% block header-css %}
    {% load bootstrap3 %}
{% endblock %}


{% block page-content %}

    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>资产</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="/index.html">主页</a>
                </li>
                <li>
                    <a href="assets.html">资产管理</a>
                </li>
                <li class="active">
                    <strong>资产</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>


    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>资产</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li><a href="#">选项 1</a>
                            </li>
                            <li><a href="#">选项 2</a>
                            </li>
                        </ul>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <form method="post" class="form-horizontal">
                        {% csrf_token %}
                        {% if form.no_field_errors %}
                            <div class="alert alert-danger" style="margin: 20px auto 0px">
                                {{ form.non_field_errors }}
                            </div>
                        {% endif %}


                        <div class="form-group">
                            <div class="col-sm-10 col-sm-offset-0">
                                <h3>基本信息</h3>
                                {% bootstrap_field form.user layout="horizontal" %}
                                {% bootstrap_field form.upart layout="horizontal" %}
                                {% bootstrap_field form.otime layout="horizontal" %}
                                {% bootstrap_field form.addr layout="horizontal" %}
                            </div>
                        </div>
                        <div class="hr-line-dashed"></div>
                        <div class="hr-line-dashed"></div>

                        <div class="form-group">
                            <div class="col-sm-4 col-sm-offset-3">

                                {% bootstrap_button "保存" button_type="submit" button_class="btn-primary" %}

                                <a class="btn btn-white" onClick="javascript :history.back(-1);">取消</a>
                            </div>
                        </div>
                    </form>


                </div>
            </div>
        </div>

    </div>


    {% block footer-js %}
<script>
        $('#id_utype').change(function(){
            var id = $('#id_utype').val();
            $.getJSON("{% url 'assets:getdate' %}?pk="+id, function(data,textStatus){
                var content='';
                $.each(data, function(i, item){
                       content+='<option value='+item.pk+'>'+item.fields.name+'</option>'
                });
                $('#id_usize').html(content)
            });
        });
    </script>
    {% endblock %}

{% endblock %}

templates/assets/assets-add-update-wj.html
{% extends "base.html" %}
{% block  title %}资产{% endblock %}
{% block header-css %}
    {% load bootstrap3 %}
{% endblock %}


{% block page-content %}

    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>资产</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="/index.html">主页</a>
                </li>
                <li>
                    <a href="cmdb.html">资产管理</a>
                </li>
                <li class="active">
                    <strong>资产</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>


    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>资产</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li><a href="#">选项 1</a>
                            </li>
                            <li><a href="#">选项 2</a>
                            </li>
                        </ul>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <form method="post" class="form-horizontal">
                        {% csrf_token %}
                        {% if form.no_field_errors %}
                            <div class="alert alert-danger" style="margin: 20px auto 0px">
                                {{ form.non_field_errors }}
                            </div>
                        {% endif %}


                        <div class="form-group">
                            <div class="col-sm-10 col-sm-offset-0">
                                <h3>基本信息</h3>
                                {% bootstrap_field form.uid layout="horizontal" %}
                                {% bootstrap_field form.utype layout="horizontal" %}
<div class="form-group has-success"><label class="col-md-3 control-label" for="id_usize">设备型号</label><div class="col-md-9">
<select name="usize" class="form-control" title="" required id="id_usize">
<option value="">---------</option>
</select></div></div>
                                {% bootstrap_field form.uconf layout="horizontal" %}
                                {% bootstrap_field form.ctime layout="horizontal" %}
                            </div>
                        </div>
                        <div class="hr-line-dashed"></div>
                        <div class="hr-line-dashed"></div>

                        <div class="form-group">
                            <div class="col-sm-4 col-sm-offset-3">

                                {% bootstrap_button "保存" button_type="submit" button_class="btn-primary" %}

                                <button class="btn btn-white" href="{{ i__next__ }}">取消</button>
                            </div>
                        </div>
                    </form>


                </div>
            </div>
        </div>

    </div>


    {% block footer-js %}
<script>
        $('#id_utype').change(function(){
            var id = $('#id_utype').val();
            $.getJSON("{% url 'assets:getdate' %}?pk="+id, function(data,textStatus){
                var content='';
                $.each(data, function(i, item){
                       content+='<option value='+item.pk+'>'+item.fields.name+'</option>'
                });
                $('#id_usize').html(content)
            });
        });
    </script>
    {% endblock %}

{% endblock %}

templates/assets/assets-update.html
{% extends "base.html" %}
{% block  title %}资产{% endblock %}
{% block header-css %}
    {% load bootstrap3 %}
{% endblock %}


{% block page-content %}

    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>资产</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="/index.html">主页</a>
                </li>
                <li>
                    <a href="assets.html">资产管理</a>
                </li>
                <li class="active">
                    <strong>资产</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>


    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>资产</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li><a href="#">选项 1</a>
                            </li>
                            <li><a href="#">选项 2</a>
                            </li>
                        </ul>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <form method="post" class="form-horizontal">
                        {% csrf_token %}
                        {% if form.no_field_errors %}
                            <div class="alert alert-danger" style="margin: 20px auto 0px">
                                {{ form.non_field_errors }}
                            </div>
                        {% endif %}


                        <div class="form-group">
                            <div class="col-sm-10 col-sm-offset-0">
                                <h3>基本信息</h3>
                                <div class="form-group"><label class="col-md-3 control-label" for="id_uid">资产编号</label><div class="col-md-9"><input type="text" name="uid" value="{{ obj.uid }}" maxlength="24" class="form-control" placeholder="资产编号" title="" required id="id_uid" readonly/></div></div>
                                {% bootstrap_field form.pid layout="horizontal" %}
                                {% bootstrap_field form.sn layout="horizontal" %}
                                {% bootstrap_field form.utype layout="horizontal" %}
<div class="form-group has-success"><label class="col-md-3 control-label" for="id_usize">设备型号</label><div class="col-md-9">
<select name="usize" class="form-control" title="" required id="id_usize">
<option value="{{ obj.usize_id }}">{{ obj.usize }}</option>
</select></div></div>
                                {% bootstrap_field form.cpu layout="horizontal" %}
                                {% bootstrap_field form.mem layout="horizontal" %}
                                {% bootstrap_field form.disk layout="horizontal" %}
                                {% bootstrap_field form.ctime layout="horizontal" %}
                                {% bootstrap_field form.addr layout="horizontal" %}
                                {% bootstrap_field form.nmac layout="horizontal" %}
                                {% bootstrap_field form.wmac layout="horizontal" %}
                                {% bootstrap_field form.ps layout="horizontal" %}
                            </div>
                        </div>
                        <div class="hr-line-dashed"></div>
                        <div class="hr-line-dashed"></div>

                        <div class="form-group">
                            <div class="col-sm-4 col-sm-offset-3">

                                {% bootstrap_button "保存" button_type="submit" button_class="btn-primary" %}

                                <a class="btn btn-white" onClick="javascript :history.back(-1);">取消</a>
                            </div>
                        </div>
                    </form>


                </div>
            </div>
        </div>

    </div>


    {% block footer-js %}
<script>
        $('#id_utype').change(function(){
            var id = $('#id_utype').val();
            $.getJSON("{% url 'assets:getdate' %}?pk="+id, function(data,textStatus){
                var content='';
                $.each(data, function(i, item){
                       content+='<option value='+item.pk+'>'+item.fields.name+'</option>'
                });
                $('#id_usize').html(content)
            });
        });
    </script>
    {% endblock %}

{% endblock %}