cmdb/urls.py
from django.urls import path

from cmdb import views

urlpatterns = [
    path('cmdb.html',views.CmdbListAll.as_view(),name='cmdb_list'),
    path('cmdb-del.html',views.CmdbDel.as_view(),name='cmdb_del'),
    path('cmdb-add-update.html',views.CmdbAdd.as_view(),name='cmdb_add'),
    path('cmdb-add-update-<int:pk>.html',views.CmdbUpdate.as_view(),name='cmdb_update'),
    path('cmdb-detail-<int:pk>.html',views.CmdbDetail.as_view(),name='cmdb_detail'),
    path('cmdb-export.html',views.CmdbExport.as_view(),name='cmdb_export'),
    path('cmdb-import.html',views.CmdbImport,name='cmdb_import'),
    path('cmdb-ztree.html', views.CmdbZtree, name='cmdb_ztree'),
    ]

app_name="cmdb"

pfdb/urls.py
from django.urls import path
from pfdb import views

urlpatterns = [
    path('pfdb.html',views.PlatfromList.as_view(),name='pfdb_list'),
    path('pfdb-add-update.html',views.PlatfromCreat.as_view(),name='pfdb_add'),
    path('pfdb-add-update-<int:pk>.html',views.PlatfromUpdate.as_view(),name='pfdb_update'),
    path('pfdb-del.html',views.PfdbDel.as_view(),name='pfdn_del'),
    ]

app_name="pfdb"

xiaoi_ops/urls.py
from django.contrib import admin
from django.urls import path,include

from index.views import login_view, index, logout_view

urlpatterns = [
    path('admin/', admin.site.urls,name='admin'),
    path('',index),
    path('index.html',index,name='index'),
    path('login.html', login_view, name='login'),
    path('logout.html', logout_view, name='logout'),
    path('cmdb/', include('cmdb.urls', namespace="cmdb", ), ),
    path('pfdb/',include('pfdb.urls',namespace="pfdb")),
    path('gzdb/', include('gzdb.urls', namespace="gzdb")),
    path('base_info/', include('base_info.urls', namespace="base_info")),
    path('assets/', include('assets.urls', namespace="assets")),
    path('tb_log/',include('tb_log.urls',namespace="tb_log")),
    path('workorder/',include('work_order.urls',namespace="order")),
]

cmdb/models.py
# Create your models here.
from django.db import models

class cmdb(models.Model):
    PLATFORM_CHOICES=(
        ("虚拟机","虚拟机"),
        ("物理机", "物理机"),
        ("其他", "其他"),
    )
    REGION_CHOICES=(
        ("香港",'香港'),
        ("上海",'上海'),
    )
    POWER_CHOICES=(
        ("是",'是'),
        ('否','否'),
    )

    MANAGER_CHOICES=(
        ('admin','admin'),
        ('其他','其他'),
    )
    PROJECT_CHOICES=(
        ('项目1','项目1'),
        ('项目2', '项目2'),
        ('项目3', '项目3'),
        ('其他', '其他')
    )

    id = models.AutoField(primary_key=True,verbose_name="id")
    UID = models.CharField(max_length=128, verbose_name='资产编号',null=True,blank=True)
    PID = models.CharField(max_length=128, verbose_name='序列号',null=True,blank=True)

    hostname = models.CharField(max_length=64, verbose_name='主机名',unique=True)
    network_ip = models.GenericIPAddressField(verbose_name='外网IP', null=True,blank=True)
    inner_ip = models.GenericIPAddressField(verbose_name='内网IP', null=True, blank=True)


    system = models.CharField(max_length=128,verbose_name='系统版本',null=True,blank=True)
    cpu = models.CharField(max_length=64,verbose_name='CPU',null=True,blank=True)
    memory = models.CharField(max_length=64, verbose_name='内存', null=True,blank=True)
    disk = models.CharField(max_length=256,verbose_name="硬盘",null=True,blank=True)
    netinfo = models.CharField(max_length=256,verbose_name="网卡",null=True,blank=True)


    platform =  models.CharField(max_length=128, choices=PLATFORM_CHOICES, verbose_name='机器类型')
    platform_size =  models.CharField(max_length=128, verbose_name='机器型号',null=True,blank=True)
    region =  models.CharField(max_length=128, choices=REGION_CHOICES, verbose_name='机柜名')
    power = models.CharField(max_length=128, choices=POWER_CHOICES, verbose_name='电源冗余')




    manager = models.CharField(max_length=128, choices=MANAGER_CHOICES, verbose_name='负责人')
    use = models.CharField(max_length=128,null=True,blank=True, verbose_name='使用人')
    project = models.CharField(max_length=128, choices=PROJECT_CHOICES, verbose_name='项目')

    ps = models.CharField(max_length=1024,verbose_name="备注（用途）",null=True,blank=True)
    # port = models.IntegerField(verbose_name="登录端口",default='22',null=True, blank=True)
    logintype = models.CharField(max_length=1024,verbose_name="登录方式",null=True,blank=True)

    ctime= models.CharField(max_length=64,null=True,verbose_name='申请时间',blank=True)
    utime = models.CharField(max_length=64,null=True,verbose_name='到期时间',blank=True)

    gtime= models.CharField(max_length=64,null=True,verbose_name='上架时间',blank=True)
    otime = models.CharField(max_length=64,null=True,verbose_name='下架时间',blank=True)





    class  Meta:
        db_table ="cmdb"
        verbose_name="资产管理"
        verbose_name_plural = '资产管理'
        permissions = {
            ('read_cmdb',u"只读资产管理"),
        }


    def __str__(self):
        return self.hostname

pfdb/models.py
# Create your models here.
from django.db import models

class pfdb(models.Model):

    id = models.AutoField(primary_key=True,verbose_name="id")
    platfrom_name = models.CharField(max_length=64,verbose_name="平台名称")
    platfrom_url = models.URLField(max_length=128,verbose_name="平台地址")
    platfrom_ps = models.CharField(max_length=128, verbose_name="备注")

    class Meta:
        db_table ="pfdb"
        verbose_name="平台管理"
        verbose_name_plural = '平台管理'

    def __str__(self):
        return self.platfrom_name

pfdb/views.py
import json

from django.shortcuts import HttpResponse
# Create your views here.
from xiaoi_ops import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, ListView, View, UpdateView
from .models import pfdb
from .form import PfdbFrom
from django.urls import reverse_lazy


class PlatfromList(LoginRequiredMixin, ListView):
    model = pfdb
    template_name = 'pfdb/pfdb.html'
    paginate_by = settings.DISPLAY_PER_PAGE
    context_object_name = 'pfdb_list'
    ordering = 'id'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = {
            "platform_class": 'active',
        }
        kwargs.update(context)
        return super().get_context_data(**kwargs)

class PlatfromCreat(LoginRequiredMixin,CreateView):
    model = pfdb
    success_url = reverse_lazy('pfdb:pfdb_list')
    form_class = PfdbFrom
    template_name = 'pfdb/pfdb-add-update.html'

class PlatfromUpdate(LoginRequiredMixin,UpdateView):

    model = pfdb
    success_url = reverse_lazy('pfdb:pfdb_list')
    form_class = PfdbFrom
    template_name = 'pfdb/pfdb-add-update.html'
    
    
class PfdbDel(LoginRequiredMixin,View):
    model = pfdb
    def post(self,request):
        ret = {'status':True,'error':None}
        try:
            if request.POST.get('nid'):
                id = request.POST.get('nid',None)
                pfdb.objects.get(id=id).delete()
            else:
                ids = request.POST.getlist('id',None)
                if len(ids) == 0:
                    ret['status'] = False
                    ret['error'] = '请选者删除的条目'
                else:
                    idstring = ','.join(ids)
                    pfdb.objects.extra(where=['id IN ('+ idstring+')']).delete()
        except Exception as e:
            ret['status'] = False
            ret['error'] = '删除错误'.format(e)
        finally:
            return HttpResponse(json.dumps(ret))

templates/pfdb/pfdb-add-update.html
{% extends "base.html" %}
{% block  title %}平台{% endblock %}
{% block header-css %}
{% load bootstrap3 %}
{% endblock %}


{% block page-content %}

    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>平台信息</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="/index.html">主页</a>
                </li>
                <li>
                    <a href="pfdb.html">平台管理</a>
                </li>
                <li class="active">
                    <strong>平台</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>


    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>平台</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li><a href="#">选项 1</a>
                            </li>
                            <li><a href="#">选项 2</a>
                            </li>
                        </ul>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">

                    <form  method="post" class="form-horizontal">
                        {% csrf_token %}
                        {% if form.no_field_errors %}
                            <div class="alert alert-danger" style="margin: 20px auto 0px">
                                {{ form.non_field_errors }}
                            </div>
                        {% endif %}

                        <div class="form-group">
                            <div class="col-sm-10 col-sm-offset-0">
                                <h3>基本信息</h3>
                                {% bootstrap_field form.platfrom_name layout="horizontal" %}
                                {% bootstrap_field form.platfrom_url layout="horizontal" %}
                                {% bootstrap_field form.platfrom_ps layout="horizontal" %}
                            </div>
                        </div>
                        <div class="hr-line-dashed"></div>




                        <div class="form-group">
                            <div class="col-sm-4 col-sm-offset-3">

                                {% bootstrap_button "保存" button_type="submit" button_class="btn-primary" %}

                                <a class="btn btn-white" href="{%  url 'pfdb:pfdb_list' %}">取消</a>
                            </div>
                        </div>

                    </form>


                </div>
            </div>
        </div>

    </div>


{% block footer-js %}

{#            $('#id_platform').change(function () {#}
{#                var name = $('#id_platform').val();#}
{##}
{#                $.getJSON("{% url 'asset:asset_getdata' %}?name=" + name, function (data, textStatus) {#}
{##}
{#                    var content = '';#}
{#                    $.each(data, function (i, item) {#}
{#                        content += '<option   value=' + item.pk + '>' + item.fields.name + '</option>'#}
{#                    });#}
{#                    $('#id_region').html(content)#}
{#                });#}
{#            });#}



{% endblock %}

{% endblock %}

templates/pfdb/pfdb.html
{% extends "base.html" %}
{% load  static %}
{% block header-css %}
    <style type="text/css">


        div#rMenu {
            position: absolute;
            visibility: hidden;
            text-align: left;
            top: 100%;
            left: 0;
            z-index: 1000;
            float: left;
            padding: 5px 0;
            margin: 2px 0 0;
            list-style: none;
            background-clip: padding-box;
        }

        div#rMenu li {
            margin: 1px 0;
            cursor: pointer;
        {#list-style: none outside none;#}
        }

        .dropdown a:hover {
            background-color: #f1f1f1
        }
    </style>

{% endblock %}

{% block  title %}平台信息{% endblock %}



{% block page-content %}
    <div class="row wrapper border-bottom white-bg page-heading ">
        <div class="col-lg-10">
            <h2>平台信息</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{% url "index" %}">主页</a>
                </li>
                <li>
                    <a>平台管理</a>
                </li>
                <li class="active">
                    <strong>平台信息</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2" id="split-left">
        </div>
    </div>

    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div  id="split-right">

                <div class="ibox float-e-margins">

                    <div class="ibox-title">
                        <h5>平台信息</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-wrench"></i>
                            </a>
                            <ul class="dropdown-menu dropdown-user">
                                <li><a href="#">选项 1</a>
                                </li>
                                <li><a href="#">选项 2</a>
                                </li>
                            </ul>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">

                        <div class="table-responsive">



                            <a href="{% url 'pfdb:pfdb_add' %}" class="btn btn-sm btn-primary ">
                                    添加</a>



                            <form id="del_form_pfdb_all" class="form-horizontal  " method="post">
                                {% csrf_token %}
                                <table class="table table-striped table-bordered table-hover dataTables-pfdb">
                                    <thead>
                                    <tr>
                                        <th width="20"><input type="checkbox" id="CheckedAll"></th>
                                        <th>平台名</th>
                                        <th>平台地址</th>
                                        <th>操作</th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    {% for   row   in   pfdb_list %}

                                        <tr class="gradeA" id="{{ row.id }}">
                                            <td><input type="checkbox" value="{{ row.id }}" name="id"></td>
                                            <td class="center">{{ row.platfrom_name}}</td>
                                            <td class="center">
                                                <a class="btn btn-primary  btn-xs " href="{{ row.platfrom_url }}" target=_blank>{{ row.platfrom_url}}</a>
                                                </td>
                                            <td><a class="btn btn-primary  btn-xs " href="{% url  "pfdb:pfdb_update" pk=row.id %}" >编辑</a>
                                                <a class="btn btn-danger  btn-xs  pfdb_del">删除</a>
                                            </td>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>

                                </table>
                                <a class="btn btn-sm btn-danger  pfdb_all_del"
                                >批量删除
                                </a>
                                <div>



                                        <ul class="pagination">
                                            <li><a href="{% url "pfdb:pfdb_list" %}?page=1">首页 </a></li>
                                            {% if  page_obj.has_previous %}
                                                <li>
                                                    <a href="{% url "pfdb:pfdb_list" %}?page={{ page_obj.previous_page_number }}&{{ search_data }}">
                                                        上一页 </a></li>
                                            {% else %}
                                                <li class="disabled"><a> 上一页 </a></li>
                                            {% endif %}

                                            {% for p in paginator.page_range %}
                                                {% if  search_data %}  <!-- 判断是否是搜索分页-->
                                                    {% if p == page_obj.number %}
                                                        <li class="active"><a
                                                                href="{% url "pfdb:pfdb_list" %}?page={{ p }}&{{ search_data }}"> {{ p }} </a>
                                                        </li>
                                                    {% else %}
                                                        <li>
                                                            <a href="{% url "pfdb:pfdb_list" %}?page={{ p }}&{{ search_data }}"> {{ p }} </a>
                                                        </li>
                                                    {% endif %}
                                                {% else %}
                                                    {% if p == page_obj.number %}
                                                        <li class="active"><a
                                                                href="{% url "pfdb:pfdb_list" %}?page={{ p }}"> {{ p }} </a>
                                                        </li>
                                                    {% else %}
                                                        <li>
                                                            <a href="{% url "pfdb:pfdb_list" %}?page={{ p }}"> {{ p }} </a>
                                                        </li>
                                                    {% endif %}
                                                {% endif %}
                                            {% endfor %}


                                            {% if  page_obj.has_next %}
                                                <li>
                                                    <a href="{% url "pfdb:pfdb_list" %}?page={{ page_obj.next_page_number }}&{{ search_data }}">
                                                        下一页 </a></li>
                                            {% endif %}
                                            <li>
                                                <a href="{% url "pfdb:pfdb_list" %}?page={{ page_obj.paginator.num_pages }}">尾页 </a>
                                            </li>
                                            <li><span style="color: #0a0a0a">总: &nbsp;{{ page_obj.paginator.num_pages }} 页 </span>
                                            </li>

                                        </ul>
                                    </center>
                                </div> <!--页码 -->


                            </form>


                        </div>

                    </div>


                </div>
            </div>
        </div>
    </div>





    {% block footer-js %}
        <script src="{% static 'js/jquery.form.min.js' %}"></script>


        <script type="text/javascript">

            $(function () {

                $(document).on('click', '.pfdb_del', function () {
                    var id = $(this).parent().parent().attr('id');
                    swal({
                        title: "你确定删除",
                        text: "你将无法恢复",
                        type: "warning",
                        showCancelButton: true,
                        confirmButtonColor: "#DD6B55",
                        confirmButtonText: "确定",
                        closeOnConfirm: false
                    }, function () {
                        $.ajax({
                            headers: {"X-CSRFToken": '{{ csrf_token }}'},
                            url: "/pfdb/pfdb-del.html",
                            type: 'POST',
                            data: {'nid': id},
                            success: function (data) {
                                var obj = JSON.parse(data);
                                if (obj.status) {
                                    swal({title: "删除", text: "已成功删除", type: "success"}, function () {
                                        window.location.reload();
                                    })
                                } else {
                                    swal("错误", "删除" + "[ " + obj.error + " ]" + "遇到错误", "error");
                                }
                            }
                        });


                    });

                });

                $(document).on('click', '.pfdb_all_del', function () {

                    swal({

                        title: "你确定删除",
                        text: "你将无法恢复",
                        type: "warning",
                        showCancelButton: true,
                        confirmButtonColor: "#DD6B55",
                        confirmButtonText: "确定",

                        closeOnConfirm: false
                    }, function () {
                        $.ajax({
                            headers: {"X-CSRFToken": '{{ csrf_token }}'},
                            url: "/pfdb/pfdb-del.html",
                            type: 'POST',
                            data: $('#del_form_pfdb_all').serialize(),
                            success: function (data) {
                                var obj = JSON.parse(data);
                                if (obj.status) {
                                    swal({title: "删除", text: "已成功删除", type: "success"}, function () {
                                        window.location.reload();
                                    })
                                } else {
                                    swal("错误", "删除" + "[ " + obj.error + " ]" + "遇到错误", "error");
                                }
                            }
                        });


                    });
                });


            });
        </script>
    {% endblock %}

    {% block footer-js-ajax %}
    {% endblock %}

{% endblock %}