assets/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django.urls import path

from assets import views

app_name = 'assets'

urlpatterns = [
    path('assets.html', views.AssetsList.as_view(), name='assets_list'),
    path('assets-add-update.html', views.AssetsAdd.as_view(), name='assets_add'),
    path('assets-update-<pk>.html', views.AssetsUpdateDtail.as_view(), name='assets_update'),
    path('assets-detail-<pk>.html', views.AssetsDetail.as_view(), name='assets_detail'),
    path('assets-wx-<pk>.html', views.repair, name='assets_log'),
    path('assets-add-update-g-<pk>.html', views.AssetsUpdate.as_view(), name='assets_update_g'),
    path('assets-add-update-o-<pk>.html', views.AssetsUpdate.as_view(), name='assets_update_o'),
    path('assets-add-update-i-<pk>.html', views.AssetsUpdatein.as_view(), name='assets_update_i'),
    path('assets-add-update-p-<pk>.html', views.AssetsUpdatein.as_view(), name='assets_update_p'),
    path('getdata.html', views.getdata, name='getdate'),
    path('assets-ztree.html', views.AssetsZtree, name='assets_ztree'),
    path('assets-export.html', views.excel_export, name='assets_export'),
    path('assets-import.html',views.AssetsImport,name='assets_import'),
    path('assets-count.html', views.assets_count, name='assets_count'),
]

base_info/urls.py
from django.urls import path

from base_info import views

urlpatterns = [
    path('person.html', views.PersonList.as_view(), name='person_list'),
    path('person-add-update.html', views.PersonAdd.as_view(), name='person_add'),
    path('person-del.html', views.PersonDel.as_view(), name='person_del'),
    path('person-add-update-<pk>.html', views.PersonUpdate.as_view(), name='person_update'),
    path('person-ztree.html', views.PersonZtree, name='person_ztree'),
    path('department.html', views.PartList.as_view(), name='part_list'),
    path('department-add-update.html', views.PartAdd.as_view(), name='part_add'),
    path('department-del.html', views.PartDel.as_view(), name='part_del'),
    path('department-add-update-<pk>.html', views.PartUpdate.as_view(), name='part_update'),

    path('shop.html', views.ShopList.as_view(), name='shop_list'),
    path('shop-add-update.html', views.ShopAdd.as_view(), name='shop_add'),
    path('shop-del.html', views.ShopDel.as_view(), name='shop_del'),
    path('shop-add-update-<pk>.html', views.ShopUpdate.as_view(), name='shop_update'),

    path('platform.html', views.PlatformList.as_view(), name='platform_list'),
    path('platform-add-update.html', views.PlatformAdd.as_view(), name='platform_add'),
    path('platformsize-add-update.html', views.Platform_sizeAdd.as_view(), name='platformsize_add'),
    # path('platformasstes-add-update.html', views.Platform_assetsAdd.as_view(), name='platformasstes_add'),
    # path('platform-del.html', views.PlatformDel.as_view(), name='platform_del'),
    # path('platform-add-update-<pk>.html', views.PlatformUpdate.as_view(), name='platform_update'),

]
app_name = 'base_info'

cmdb/urls.py
from django.urls import path

from cmdb import views

urlpatterns = [
    path('cmdb.html',views.CmdbListAll.as_view(),name='cmdb_list'),
    path('cmdb-del.html',views.CmdbDel.as_view(),name='cmdb_del'),
    path('cmdb-add-update.html',views.CmdbAdd.as_view(),name='cmdb_add'),
    path('cmdb-add-update-<int:pk>.html',views.CmdbUpdate.as_view(),name='cmdb_update'),
    path('cmdb-detail-<int:pk>.html',views.CmdbDetail.as_view(),name='cmdb_detail'),
    path('cmdb-export.html',views.CmdbExport.as_view(),name='cmdb_export'),
    path('cmdb-import.html',views.CmdbImport,name='cmdb_import'),
    path('cmdb-ztree.html', views.CmdbZtree, name='cmdb_ztree'),
    ]

app_name="cmdb"

pfdb/urls.py
from django.urls import path
from pfdb import views

urlpatterns = [
    path('pfdb.html',views.PlatfromList.as_view(),name='pfdb_list'),
    path('pfdb-add-update.html',views.PlatfromCreat.as_view(),name='pfdb_add'),
    path('pfdb-add-update-<int:pk>.html',views.PlatfromUpdate.as_view(),name='pfdb_update'),
    path('pfdb-del.html',views.PfdbDel.as_view(),name='pfdn_del'),
    ]

app_name="pfdb"

tb_log/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.urls import path
from tb_log import views

app_name = 'tb_log'

urlpatterns = [
    path('tb_log-<kw>-<pk>-<user>.html', views.logcreate, name='tb_log_create'),
    path('tb_log.html', views.LogView.as_view(), name='tb_log_list'),
    # path('assets-add-update.html', views.AssetsAdd.as_view(), name='assets_add'),
    # path('assets-detail-<pk>.html', views.AssetsDetail.as_view(), name='assets_detail'),
    # path('assets-add-update-g-<pk>.html', views.AssetsUpdate.as_view(), name='assets_update_g'),
    # path('assets-add-update-o-<pk>.html', views.AssetsUpdate.as_view(), name='assets_update_o'),
    # path('assets-add-update-i-<pk>.html', views.AssetsUpdatein.as_view(), name='assets_update_i'),
    # path('getdata.html', views.getdata, name='getdate'),
]

xiaoi_ops/urls.py
from django.contrib import admin
from django.urls import path,include

from index.views import login_view, index, logout_view

urlpatterns = [
    path('admin/', admin.site.urls,name='admin'),
    path('',index),
    path('index.html',index,name='index'),
    path('login.html', login_view, name='login'),
    path('logout.html', logout_view, name='logout'),
    path('cmdb/', include('cmdb.urls', namespace="cmdb", ), ),
    path('pfdb/',include('pfdb.urls',namespace="pfdb")),
    path('gzdb/', include('gzdb.urls', namespace="gzdb")),
    path('base_info/', include('base_info.urls', namespace="base_info")),
    path('assets/', include('assets.urls', namespace="assets")),
    path('tb_log/',include('tb_log.urls',namespace="tb_log")),
    path('workorder/',include('work_order.urls',namespace="order")),
]

templates/_css.html
{% load  static %}

<link rel="icon" href={% static  "css/favicon.ico" %}" mce_href= {% static  "css/favicon.ico" %}" type="image/x-icon">

<link href=" {% static  "css/bootstrap.min.css" %}" rel="stylesheet">

<link href="{% static  "font-awesome/css/font-awesome.css" %}" rel="stylesheet">

<link href="{% static  "css/animate.css" %}" rel="stylesheet">

<link href="{% static "css/style.css"  %} " rel="stylesheet">

<link href="{% static "css/datatables.min.css"%} "   rel="stylesheet">

<link href="{% static "css/plugins/select2/select2.min.css"%} "   rel="stylesheet">

<link href="{% static  "css/plugins/sweetalert/sweetalert.css"%}" rel="stylesheet">

<link href="{% static "css/animate.css"%}" rel="stylesheet">

<link href="{% static "css/style.css"%}" rel="stylesheet">

<!-- Toastr style -->
<link  href="{% static  "css/plugins/toastr/toastr.min.css" %}"  rel="stylesheet">

templates/_footer.html
  <div class="footer">
            <div class="pull-right">
                <strong>IT管理系统</strong>
            </div>
            <div>
                <strong>Copyright</strong> Example Company &copy; 2018-2020
            </div>
        </div>

templates/_js.html
{% load  static %}

<script src="{% static  "js/jquery-3.1.1.min.js"%}"></script>
<script src="{% static  "js/bootstrap.min.js"%}"></script>
<script src="{% static  "js/plugins/metisMenu/jquery.metisMenu.js"%}"></script>
<script src="{% static  "js/plugins/slimscroll/jquery.slimscroll.min.js"%}"></script>

<!-- Custom and plugin javascript -->
<script src="{% static  "js/inspinia.js"%} "></script>
<script src="{% static  "js/plugins/pace/pace.min.js"%}"></script>


<script src="{% static  "js/datatables.min.js" %}"></script>


<script src="{% static  "js/plugins/select2/select2.full.min.js" %}"></script>


<!-- Sweet alert -->
<script src="{% static  "js/plugins/sweetalert/sweetalert.min.js" %}"></script>

 <!-- Toastr script -->
<script src="{% static  "js/plugins/toastr/toastr.min.js"%}"></script>

<script type="text/javascript" src="{% static 'js/plugins/ztree/jquery.ztree.all.min.js' %}"></script>



<!-- Page-Level Scripts -->
<script>
   $(document).ready(function () {



         $('.dataTables-example').DataTable({

            "oLanguage": {
                "sLengthMenu": "每页显示 _MENU_ 条记录",
                "sZeroRecords": "对不起，查询不到任何相关数据",
                "sInfo": "当前显示 _START_ 到 _END_ 条，共 _TOTAL_条记录",
                "sInfoEmtpy": "找不到相关数据",
                "sInfoFiltered": " 数据表中共为 _MAX_ 条记录",
                "sProcessing": "正在加载中...",
                "sSearch": "搜索",
                "oPaginate": {
                    "sFirst": "第一页",
                    "sPrevious": " 上一页 ",
                    "sNext": " 下一页 ",
                    "sLast": " 最后一页 "
                }
            },
            "order": [[1, 'desc']],
            destroy:true,
            columnDefs: [{
                'targets': [0],    //都默认不排序
                'orderable': false
            }],


            dom: '<"html5buttons"B>lTfgitp,',

            buttons: [],
            lengthMenu: [[15, 40, 70, -1], [15, 40, 70, "全部"]]
        });

    });


   $("#CheckedAll").click(function () {
        if ($(this).is(":checked")) {
            $("[name=id]:checkbox").prop("checked", true);
        } else {
            $("[name=id]:checkbox").prop("checked", false);
        }
    });

    </script>

templates/_nav.html
<nav class="navbar-default navbar-static-side  " role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <span class="clear"> <span class="block m-t-xs"> <strong
                                    class="font-bold">{{ user }}</strong>

                             </span> <span class="text-muted text-xs block">
                                {% ifequal  user.is_superuser  1 %}
                                    管理员 {% else %} 普通用户 {% endifequal %}
                                <b class="caret"></b></span> </span>
                    </a>
                    <ul class="dropdown-menu animated fadeInRight m-t-xs">
                        {#                        <li><a href="">修改密码</a></li>#}
                        <li><a href="/logout.html">登出</a></li>
                    </ul>
                </div>
                <div class="logo-element">
                    autoops
                </div>
            </li>
            <li>
                <a href="{% url "index" %}"><i class="fa fa-th-list"></i> <span class="nav-label">首页</span>
                </a>

            </li>
            <li class="{{ base_info_class }}">
                <a href="#"><i class="fa fa-inbox"></i> <span class="nav-label">基础信息</span>
                    <span class="fa arrow"> </span></a>
                <ul class="nav nav-second-level">
                    <li><a href="{% url "base_info:person_list" %}">员工管理</a></li>
                </ul>
                <ul class="nav nav-second-level">
                    <li><a href="{% url "base_info:part_list" %}">部门管理</a></li>
                </ul>
                <ul class="nav nav-second-level">
                    <li><a href="{% url "base_info:shop_list" %}">商家管理</a></li>
                </ul>
                <ul class="nav nav-second-level">
                    <li><a href="{% url "base_info:platform_list" %}">设备管理</a></li>
                </ul>
            </li>
            <li class="{{ platform_class }}">
                <a href="#"><i class="fa fa-inbox"></i> <span class="nav-label">平台管理</span>
                    <span class="fa arrow"> </span></a>
                <ul class="nav nav-second-level">
                    <li><a href="{% url "pfdb:pfdb_list" %}">平台信息</a></li>
                </ul>
            </li>

                    <li class="{{ assets_class }}">
                        <a href="#"><i class="fa fa-inbox"></i> <span class="nav-label">内网资产管理</span>
                    <span class="fa arrow"> </span></a>
                <ul class="nav nav-second-level">
                    <li ><a href="{% url "assets:assets_list" %}">固资管理</a></li>
                    <li ><a href="{% url "tb_log:tb_log_list" %}">操作记录</a></li>
                    <li><a href="{% url "assets:assets_count" %}">资产统计</a></li>
                    <li ><a href="{% url "assets:assets_import" %}">资产导入</a></li>
{#                    <li ><a href="{% url "pfdb:pfdb_list" %}">资产入库</a></li>#}
                </ul>
            </li>
            <li class="{{ cmdb_class }}">
                <a href="#"><i class="fa fa-inbox"></i> <span class="nav-label">外网资产管理</span>
                    <span class="fa arrow"> </span></a>
                <ul class="nav nav-second-level">
                    <li ><a href="{% url "cmdb:cmdb_list" %}">资产信息</a></li>
                    <li ><a href="{% url "cmdb:cmdb_import" %}">资产导入</a></li>


                </ul>
            </li>

            <li class="{{ order_class }}">
                <a href="#"><i class="fa fa-inbox"></i> <span class="nav-label">工作管理</span>
                    <span class="fa arrow"> </span></a>
                <ul class="nav nav-second-level">
                    <li><a href="{% url "order:order_list" %}">工作日志</a></li>

                </ul>
            </li>


            {#            <li>#}
            {#                <a href="#"><i class="fa fa-inbox"></i> <span class="nav-label">管理</span>#}
            {#                    <span class="fa arrow"> </span></a>#}
            {#                <ul class="nav nav-second-level">#}
            {##}
            {#                    <li ><a href="{% url "pfdb:pfdb_list" %}">后台管理</a></li>#}
            {#                </ul>#}
            {#            </li>#}

        </ul>

    </div>
</nav>

templates/_navbar-static-top.html
<div class="row border-bottom">
            <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
                <div class="navbar-header">
                    <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
{#                    <form role="search" class="navbar-form-custom" method="post" action="#">#}
{#                        <div class="form-group">#}
{#                            <input type="text" placeholder="请输入搜索内容" class="form-control" name="top-search" id="top-search">#}
{#                        </div>#}
{#                    </form>#}
                </div>
                <ul class="nav navbar-top-links navbar-right">
                    欢迎 {{  user  }} 使用   &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                    <li>
                        <a href="{% url 'logout' %}">
                            <i class="fa fa-sign-out"></i> 注销
                        </a>
                    </li>
                </ul>

            </nav>
        </div>

templates/base.html
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% block  title %}{% endblock %}</title>

    {% include  "_css.html" %}
    {% block header-css %}
    {% endblock %}


</head>

<body>
<div id="wrapper" class="container1">


    {% include "_nav.html" %}

    <div id="page-wrapper" class="gray-bg">
        {% include  "_navbar-static-top.html" %}

        {% block page-content %}


        {% endblock %}
        {% include  "_footer.html" %}

    </div>
</div>


<div id="terminal"></div>
{% include  "_js.html" %}
{% block footer-js %}

{% endblock %}

{% block footer-js-ajax %}
    <script type="text/JavaScript">
        $.ajaxSetup({headers: {"X-CSRFToken": '{{ csrf_token }}'}});
    </script>
{% endblock %}
</body>

</html>